"use client";

import { useMemo, useState } from "react";
import { RHEA_FLINT, TRAINING_FOCI, TRAINING_UPGRADES, getRanchMaterialStock, getTrainingAssignment, getTrainingCreatureLabel, getTrainingCount, getTrainingHistorySummary, getTrainingStatusLabel, getTrainingUpgrade, getTrainingUpgradeEffects, hasTrainingUpgrade } from "@/data/trainingGrounds";
import { getVariantDefinition } from "@/data/creatures";
import { formatGold } from "@/lib/formatters";
import { useGameContext } from "@/state/GameProvider";
import type { CreatureRecord, CreatureStatKey } from "@/types/creature";
import type { CreatureId } from "@/types/ids";
import type { TrainingFocus, TrainingFocusId, TrainingRewardSummary, TrainingUpgrade, TrainingUpgradeId } from "@/data/trainingGrounds";
import styles from "@/features/market/MarketScreen.module.css";

const ICONS = { grounds: "/images/backgrounds/ranch/ranch_office_interior.png", rhea: RHEA_FLINT.portraitPath, whistle: "/images/ui/icons/icon_breeder_level.png", price: "/images/ui/icons/icon_price_tag.png", energy: "/images/ui/icons/icon_sleep_recovery.png", xp: "/images/ui/icons/icon_breeder_level.png", stat: "/images/ui/icons/icon_stat_grade.png", materials: "/images/ui/icons/icon_ranch_upgrade.png", drillStation: "/images/props/town/training_grounds_drill_station.png", upgradeBench: "/images/props/town/training_grounds_upgrade_bench.png", statBoard: "/images/props/town/training_grounds_stat_coaching_board.png" } as const;
const RHEA_GREETING = "Pick a creature and a focus. Training now means leaving them with me for a few days. While they are here, they are unavailable for other work.";
const STAT_OPTIONS: CreatureStatKey[] = ["STR", "DEX", "STA", "CHA", "WIL", "FER"];
type TrainingMode = "interior" | "train" | "talk" | "records" | "upgrades";

function getPanelStyle() { return { position: "relative", zIndex: 3, padding: 18, border: "1px solid rgba(245,201,128,.55)", borderRadius: 4, background: "rgba(21, 10, 5, .72)", color: "#fff0c9", boxShadow: "0 14px 34px rgba(0,0,0,.42)", backdropFilter: "blur(2px)" } as const; }
function getInteriorButtonStyle() { return { display: "grid", gap: 4, justifyItems: "center", minWidth: 220, padding: "18px 20px", border: "2px solid rgba(245,201,128,.72)", borderRadius: 4, background: "rgba(0,0,0,.42)", color: "#fff7dd", boxShadow: "0 14px 28px rgba(0,0,0,.35)", cursor: "pointer" } as const; }
function getCreatureImage(creature: CreatureRecord): string { return getVariantDefinition(creature.variantId).portraitPath; }
function getBestStatLabel(creature: CreatureRecord): string { const order = ["D", "C", "B", "A", "S"]; const best = Object.entries(creature.statGrades).sort((a, b) => order.indexOf(b[1]) - order.indexOf(a[1]))[0]; return best ? `${best[0]} ${best[1]}` : "No stat grades"; }
function xpText(reward: TrainingRewardSummary) { return reward.levelBefore === reward.levelAfter ? `${reward.xpBefore}/${reward.xpToNextBefore} → ${reward.xpAfter}/${reward.xpToNextAfter}` : `Lv. ${reward.levelBefore} ${reward.xpBefore}/${reward.xpToNextBefore} → Lv. ${reward.levelAfter} ${reward.xpAfter}/${reward.xpToNextAfter}`; }
function creaturesInTraining(save: NonNullable<ReturnType<typeof useGameContext>["currentSave"]>): number { return (save.creatures ?? []).filter((creature) => getTrainingAssignment(save, creature.creatureId)).length; }

export function TrainingGroundsScreen() {
  const { collectTrainingCreature, currentSave, goToMainMenu, goToTown, purchaseTrainingGroundsUpgrade, saveCurrentGame, trainCreature } = useGameContext();
  const [message, setMessage] = useState(RHEA_GREETING);
  const [trainingMode, setTrainingMode] = useState<TrainingMode>("interior");
  const [selectedCreatureId, setSelectedCreatureId] = useState<CreatureId | null>(null);
  const [targetStat, setTargetStat] = useState<CreatureStatKey>("STR");
  const [lastReward, setLastReward] = useState<TrainingRewardSummary | null>(null);
  const creatures = useMemo(() => currentSave?.creatures ?? [], [currentSave]);
  const selectedCreature = useMemo(() => creatures.find((creature) => creature.creatureId === selectedCreatureId) ?? creatures[0] ?? null, [creatures, selectedCreatureId]);
  if (!currentSave) return <main className={styles.emptyScreen}><section className={styles.emptyPanel}><h1>No active save</h1><p>Load or create a save before entering the Training Grounds.</p><button type="button" onClick={goToMainMenu}>Return to Main Menu</button></section></main>;
  function runTraining(focusId: TrainingFocusId) { if (!selectedCreature) return; const result = trainCreature(selectedCreature.creatureId, focusId, focusId === "focused_stat_coaching" ? targetStat : undefined); if (result.ok) saveCurrentGame(result.save); setLastReward(null); setMessage(result.message); setTrainingMode("train"); }
  function collectTraining(creatureId: CreatureId) { const result = collectTrainingCreature(creatureId); if (result.ok) saveCurrentGame(result.save); setLastReward(result.reward ?? null); setMessage(result.message); setTrainingMode("train"); }
  function buyUpgrade(upgradeId: TrainingUpgradeId) { const result = purchaseTrainingGroundsUpgrade(upgradeId); if (result.ok) saveCurrentGame(result.save); setMessage(result.message); setTrainingMode("upgrades"); }
  function openTalk() { setMessage("Rhea folds her arms. 'No more instant drills. Leave them with me, give the work time, then come back for the result.'"); setTrainingMode("talk"); }
  const activeAssignments = creatures.filter((creature) => getTrainingAssignment(currentSave, creature.creatureId)).length;
  const readyAssignments = creatures.filter((creature) => getTrainingAssignment(currentSave, creature.creatureId)?.isReady).length;
  const effects = getTrainingUpgradeEffects(currentSave);
  const materials = getRanchMaterialStock(currentSave);
  return <main className={styles.screen}><section className={styles.frame}><div className={styles.backgroundArt} aria-hidden="true" /><div className={styles.shade} aria-hidden="true" /><header className={styles.header}><div><p className={styles.kicker}>M50 Training Polish</p><h1>Training Grounds</h1><p>{RHEA_FLINT.name}, {RHEA_FLINT.title}, runs timed creature improvement programs for XP and stat growth.</p><p className={styles.message}>{message}</p></div><div className={styles.headerActions}><div className={styles.statBox}><span>Gold</span><strong>{formatGold(currentSave.currencies.gold)}</strong></div><div className={styles.statBox}><span>Materials</span><strong>{materials}</strong></div><div className={styles.statBox}><span>Capacity</span><strong>{activeAssignments}/{effects.maxAssignments}</strong></div><div className={styles.statBox}><span>Ready</span><strong>{readyAssignments} pickup</strong></div><button type="button" className={styles.backButton} onClick={goToTown}>Back to Town</button><button type="button" className={styles.backButton} onClick={goToMainMenu}>Main Menu</button></div></header>{trainingMode === "interior" ? <TrainingInterior creatureCount={creatures.length} activeAssignments={activeAssignments} maxAssignments={effects.maxAssignments} onTalk={openTalk} onTrain={() => setTrainingMode("train")} onRecords={() => setTrainingMode("records")} onUpgrades={() => setTrainingMode("upgrades")} /> : null}{trainingMode === "talk" ? <RheaTalkPanel onBack={() => setTrainingMode("interior")} onTrain={() => setTrainingMode("train")} onUpgrades={() => setTrainingMode("upgrades")} /> : null}{trainingMode === "records" ? <TrainingRecordsPanel creatures={creatures} save={currentSave} onBack={() => setTrainingMode("interior")} onTrain={() => setTrainingMode("train")} onCollect={collectTraining} /> : null}{trainingMode === "upgrades" ? <TrainingUpgradesPanel save={currentSave} onBack={() => setTrainingMode("interior")} onBuyUpgrade={buyUpgrade} /> : null}{trainingMode === "train" ? <TrainingPanel save={currentSave} creatures={creatures} selectedCreature={selectedCreature} setSelectedCreatureId={setSelectedCreatureId} targetStat={targetStat} setTargetStat={setTargetStat} onTrain={runTraining} onCollect={collectTraining} onBack={() => setTrainingMode("interior")} /> : null}{lastReward ? <TrainingRewardModal reward={lastReward} onClose={() => setLastReward(null)} /> : null}</section></main>;
}

function TrainingInterior({ creatureCount, activeAssignments, maxAssignments, onTalk, onTrain, onRecords, onUpgrades }: { creatureCount: number; activeAssignments: number; maxAssignments: number; onTalk: () => void; onTrain: () => void; onRecords: () => void; onUpgrades: () => void }) {
  return <section aria-label="Training Grounds interior" style={{ position: "relative", zIndex: 2, minHeight: "calc(100vh - 230px)", padding: "28px 34px 34px", overflow: "hidden" }}><div aria-hidden="true" style={{ position: "absolute", inset: 0, background: `linear-gradient(180deg, rgba(0,0,0,.10), rgba(0,0,0,.58)), url(${ICONS.grounds}) center/cover`, opacity: .44 }} /><div style={{ position: "relative", zIndex: 3, display: "grid", gridTemplateColumns: "minmax(260px, 360px) minmax(0, 1fr)", gap: 26, alignItems: "end", minHeight: "58vh" }}><aside style={getPanelStyle()}><div style={{ display: "grid", gridTemplateColumns: "76px minmax(0,1fr)", gap: 12, alignItems: "center" }}><img src={ICONS.rhea} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} style={{ width: 76, height: 76, objectFit: "cover", borderRadius: 999, border: "1px solid rgba(245,201,128,.55)" }} /><div><p className={styles.kicker}>Coach</p><h2 style={{ margin: 0 }}>Rhea Flint</h2><p style={{ margin: "6px 0 0" }}>{creatureCount} creatures • {activeAssignments}/{maxAssignments} training</p></div></div><p style={{ marginTop: 16, lineHeight: 1.55 }}>{RHEA_GREETING}</p><div style={{ display: "grid", gap: 8 }}><button type="button" className={styles.buyButton} onClick={onTalk}>Talk to Rhea</button><button type="button" className={styles.buyButton} onClick={onTrain}>Start Training</button><button type="button" className={styles.buyButton} onClick={onRecords}>Training Records</button><button type="button" className={styles.buyButton} onClick={onUpgrades}>Trainer Upgrades</button></div></aside><div style={{ position: "relative", minHeight: 430 }}><button type="button" style={{ ...getInteriorButtonStyle(), position: "absolute", left: "10%", top: "38%" }} onClick={onTrain}><img src={ICONS.drillStation} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} style={{ width: 76, height: 76, objectFit: "contain" }} /><strong>Training Yard</strong><span style={{ color: "#7fdbff", fontWeight: 900 }}>Leave creature • Return later</span></button><button type="button" style={{ ...getInteriorButtonStyle(), position: "absolute", right: "7%", top: "31%" }} onClick={onTalk}><img src={ICONS.rhea} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} style={{ width: 66, height: 66, objectFit: "cover", borderRadius: 999 }} /><strong>Rhea Flint</strong><span style={{ color: "#7fdbff", fontWeight: 900 }}>Talk • Advice</span></button><button type="button" style={{ ...getInteriorButtonStyle(), position: "absolute", left: "39%", bottom: "8%" }} onClick={onUpgrades}><img src={ICONS.upgradeBench} alt="" onError={(event) => { event.currentTarget.src = ICONS.stat; }} style={{ width: 76, height: 76, objectFit: "contain" }} /><strong>Upgrade Bench</strong><span style={{ color: "#7fdbff", fontWeight: 900 }}>XP • Chance • Capacity</span></button></div></div></section>;
}

function RheaTalkPanel({ onBack, onTrain, onUpgrades }: { onBack: () => void; onTrain: () => void; onUpgrades: () => void }) { return <section style={{ position: "relative", zIndex: 3, padding: 24, display: "grid", gridTemplateColumns: "320px minmax(0, 1fr)", gap: 18 }}><aside style={getPanelStyle()}><img src={ICONS.rhea} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} style={{ width: "100%", maxHeight: 280, objectFit: "cover", borderRadius: 8, border: "1px solid rgba(245,201,128,.45)" }} /><h2>Rhea Flint</h2><p>{RHEA_FLINT.title}</p></aside><section style={getPanelStyle()}><p className={styles.kicker}>Conversation</p><h2>Training Takes Time</h2><p style={{ fontSize: "1.05rem", lineHeight: 1.65 }}>"If you want the work to matter, you leave the creature with me and come back when the program is done. Better equipment does not remove the work, but it does make the work more reliable."</p><p style={{ lineHeight: 1.6 }}>Training upgrades now cost Gold and Materials. The assistant and advanced license also require earlier facilities.</p><div style={{ display: "flex", flexWrap: "wrap", gap: 10 }}><button type="button" className={styles.buyButton} onClick={onTrain}>Start Training</button><button type="button" className={styles.buyButton} onClick={onUpgrades}>Trainer Upgrades</button><button type="button" className={styles.backButton} onClick={onBack}>Back to Grounds</button></div></section></section>; }

function TrainingRecordsPanel({ creatures, save, onBack, onTrain, onCollect }: { creatures: CreatureRecord[]; save: NonNullable<ReturnType<typeof useGameContext>["currentSave"]>; onBack: () => void; onTrain: () => void; onCollect: (creatureId: CreatureId) => void }) { return <section style={{ position: "relative", zIndex: 3, padding: 24, display: "grid", gridTemplateColumns: "320px minmax(0, 1fr)", gap: 18 }}><aside style={getPanelStyle()}><h2>Training Records</h2><p>Assignments are stored per creature. When the return day arrives, collect the creature to apply the result and see the before/after report.</p><button type="button" className={styles.buyButton} onClick={onTrain}>Start Training</button><button type="button" className={styles.backButton} onClick={onBack}>Back to Grounds</button></aside><section style={getPanelStyle()}><h2>Current Assignments</h2><div className={styles.listings}>{creatures.map((creature) => { const assignment = getTrainingAssignment(save, creature.creatureId); return <article key={creature.creatureId} className={styles.listing}><div className={styles.listingArt}><img src={getCreatureImage(creature)} alt="" /></div><div className={styles.listingBody}><h3 className={styles.listingName}>{creature.nickname}</h3><p className={styles.listingDesc}>{getTrainingStatusLabel(save, creature.creatureId)}</p><p className={styles.gradePreview}>{getTrainingHistorySummary(save, creature.creatureId)}</p>{assignment ? <div className={styles.actions}><button type="button" className={styles.buyButton} disabled={!assignment.isReady} onClick={() => onCollect(creature.creatureId)}>{assignment.isReady ? "Collect + View Result" : `${assignment.daysRemaining} day(s) left`}</button></div> : null}</div></article>; })}</div></section></section>; }

function TrainingPanel({ save, creatures, selectedCreature, setSelectedCreatureId, targetStat, setTargetStat, onTrain, onCollect, onBack }: { save: NonNullable<ReturnType<typeof useGameContext>["currentSave"]>; creatures: CreatureRecord[]; selectedCreature: CreatureRecord | null; setSelectedCreatureId: (id: CreatureId) => void; targetStat: CreatureStatKey; setTargetStat: (stat: CreatureStatKey) => void; onTrain: (focusId: TrainingFocusId) => void; onCollect: (creatureId: CreatureId) => void; onBack: () => void }) {
  const selectedAssignment = selectedCreature ? getTrainingAssignment(save, selectedCreature.creatureId) : null; const effects = getTrainingUpgradeEffects(save);
  return <section className={styles.grid} style={{ position: "relative", zIndex: 3, padding: "14px 18px 24px" }}><aside className={styles.panel}><h2>Select Creature</h2><div className={styles.sideList}>{creatures.map((creature) => <button key={creature.creatureId} type="button" className={styles.infoCard} onClick={() => setSelectedCreatureId(creature.creatureId)}><img src={getCreatureImage(creature)} alt="" /><span>{getVariantDefinition(creature.variantId).name}</span><strong>{getTrainingCreatureLabel(creature)}</strong><em>{getTrainingStatusLabel(save, creature.creatureId)}</em></button>)}<button type="button" className={styles.backButton} onClick={onBack}>Back to Grounds</button></div></aside><section className={styles.panel}><h2>{selectedCreature ? `${selectedCreature.nickname}'s Training` : "No Creature Selected"}</h2>{selectedCreature ? <article className={styles.listing}><div className={styles.listingArt}><img src={getCreatureImage(selectedCreature)} alt="" /></div><div className={styles.listingBody}><span className={styles.listingMeta}>{getVariantDefinition(selectedCreature.variantId).family} • {getVariantDefinition(selectedCreature.variantId).rarity}</span><h3 className={styles.listingName}>{getTrainingCreatureLabel(selectedCreature)}</h3><p className={styles.listingDesc}>Best stat: {getBestStatLabel(selectedCreature)} • Affection {selectedCreature.affection}/100</p><p className={styles.gradePreview}>{getTrainingStatusLabel(save, selectedCreature.creatureId)}</p><p className={styles.gradePreview}>{getTrainingHistorySummary(save, selectedCreature.creatureId)}</p>{effects.focusedTrainingUnlocked ? <label style={{ display: "grid", gap: 6, margin: "8px 0", color: "#fff0c9", fontWeight: 900 }}>Focused target stat<select value={targetStat} onChange={(event) => setTargetStat(event.target.value as CreatureStatKey)} style={{ minHeight: 36, borderRadius: 10, border: "1px solid rgba(245,201,128,.35)", background: "rgba(0,0,0,.42)", color: "#fff7dd", padding: "0 10px" }}>{STAT_OPTIONS.map((stat) => <option key={stat} value={stat}>{stat} • Grade {selectedCreature.statGrades[stat]} • Stat {selectedCreature.stats[stat]}</option>)}</select></label> : null}{selectedAssignment ? <div className={styles.actions}><button type="button" className={styles.buyButton} disabled={!selectedAssignment.isReady} onClick={() => onCollect(selectedCreature.creatureId)}>{selectedAssignment.isReady ? "Collect Training Result" : `${selectedAssignment.daysRemaining} day(s) left`}</button></div> : null}</div></article> : null}<div className={styles.listings}>{TRAINING_FOCI.map((focus) => <TrainingFocusCard key={focus.focusId} save={save} creature={selectedCreature} focus={focus} onTrain={onTrain} targetStat={targetStat} />)}</div></section></section>;
}

function TrainingFocusCard({ save, creature, focus, onTrain, targetStat }: { save: NonNullable<ReturnType<typeof useGameContext>["currentSave"]>; creature: CreatureRecord | null; focus: TrainingFocus; onTrain: (focusId: TrainingFocusId) => void; targetStat: CreatureStatKey }) { const canAfford = save.currencies.gold >= focus.costGold; const assignment = creature ? getTrainingAssignment(save, creature.creatureId) : null; const effects = getTrainingUpgradeEffects(save); const locked = Boolean(focus.requiresUpgradeId && !hasTrainingUpgrade(save, focus.requiresUpgradeId)); const targetS = creature && focus.focusId === "focused_stat_coaching" ? creature.statGrades[targetStat] === "S" : false; const full = effects.maxAssignments <= creaturesInTraining(save); return <article className={`${styles.listing} ${locked ? styles.sold : ""}`}><div className={styles.listingArt}><img src={focus.iconPath} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} /></div><div className={styles.listingBody}><span className={styles.listingMeta}>{focus.category} • {focus.durationDays} day(s)</span><h3 className={styles.listingName}>{focus.name}</h3><p className={styles.listingDesc}>{focus.description}</p><p className={styles.gradePreview}>{focus.focusId === "level_drill" ? `Current result: +${effects.levelDrillXp} XP.` : focus.focusId === "focused_stat_coaching" ? `Current result: ${effects.statCoachingChance}% chance targeting ${targetStat}.` : `Current result: ${effects.statCoachingChance}% chance targeting lowest eligible stat.`}</p><p className={styles.gradePreview}>{focus.effectLabel}</p><div className={styles.price}><img src={ICONS.price} alt="" /><div><span>Cost</span><strong>{formatGold(focus.costGold)}</strong>{creature ? <em>Completed {getTrainingCount(save, creature.creatureId, focus.focusId)} time(s) for this creature.</em> : null}{locked ? <em>Requires upgrade: Advanced Training License.</em> : null}{targetS ? <em>{targetStat} is already Grade S.</em> : null}{full ? <em>Training capacity is full.</em> : null}</div></div><div className={styles.actions}><button type="button" className={styles.buyButton} disabled={!creature || !canAfford || Boolean(assignment) || locked || targetS || full} onClick={() => onTrain(focus.focusId)}>{assignment ? "Already Training" : locked ? "Locked" : "Leave with Rhea"}</button></div></div></article>; }

function TrainingUpgradesPanel({ save, onBack, onBuyUpgrade }: { save: NonNullable<ReturnType<typeof useGameContext>["currentSave"]>; onBack: () => void; onBuyUpgrade: (upgradeId: TrainingUpgradeId) => void }) { const effects = getTrainingUpgradeEffects(save); return <section className={styles.grid} style={{ position: "relative", zIndex: 3, padding: "14px 18px 24px" }}><aside className={styles.panel}><h2>Trainer Upgrades</h2><p>Upgrade Rhea's building with Gold and Materials to make training more valuable without making it instant.</p><div className={styles.sideList}><div className={styles.infoCard}><span>Materials</span><strong>{getRanchMaterialStock(save)} stock</strong></div><div className={styles.infoCard}><span>Level Drill</span><strong>{effects.levelDrillXp} XP</strong></div><div className={styles.infoCard}><span>Stat Coaching</span><strong>{effects.statCoachingChance}%</strong></div><div className={styles.infoCard}><span>Capacity</span><strong>{effects.maxAssignments} creature(s)</strong></div><div className={styles.infoCard}><span>Focused Training</span><strong>{effects.focusedTrainingUnlocked ? "Unlocked" : "Locked"}</strong></div><button type="button" className={styles.backButton} onClick={onBack}>Back to Grounds</button></div></aside><section className={styles.panel}><h2>Available Upgrades</h2><div className={styles.listings}>{TRAINING_UPGRADES.map((upgrade) => <TrainingUpgradeCard key={upgrade.upgradeId} save={save} upgrade={upgrade} onBuyUpgrade={onBuyUpgrade} />)}</div></section></section>; }
function TrainingUpgradeCard({ save, upgrade, onBuyUpgrade }: { save: NonNullable<ReturnType<typeof useGameContext>["currentSave"]>; upgrade: TrainingUpgrade; onBuyUpgrade: (upgradeId: TrainingUpgradeId) => void }) { const owned = hasTrainingUpgrade(save, upgrade.upgradeId); const canAffordGold = save.currencies.gold >= upgrade.costGold; const materialStock = getRanchMaterialStock(save); const canAffordMaterials = materialStock >= upgrade.materialCost; const prerequisiteMet = !upgrade.requiredUpgradeId || hasTrainingUpgrade(save, upgrade.requiredUpgradeId); const prerequisiteName = upgrade.requiredUpgradeId ? getTrainingUpgrade(upgrade.requiredUpgradeId)?.name : null; return <article className={`${styles.listing} ${owned ? styles.sold : ""}`}><div className={styles.listingArt}><img src={upgrade.iconPath} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} /></div><div className={styles.listingBody}><span className={styles.listingMeta}>{owned ? "Installed" : prerequisiteMet ? "Upgrade" : "Prerequisite Needed"}</span><h3 className={styles.listingName}>{upgrade.name}</h3><p className={styles.listingDesc}>{upgrade.description}</p><p className={styles.gradePreview}>{upgrade.effectLabel}</p>{prerequisiteName ? <p className={styles.gradePreview}>Requires: {prerequisiteName}</p> : null}<div className={styles.price}><img src={ICONS.price} alt="" /><div><span>Cost</span><strong>{formatGold(upgrade.costGold)} • {upgrade.materialCost} Materials</strong>{owned ? <em>Already installed.</em> : !prerequisiteMet ? <em>Install {prerequisiteName} first.</em> : !canAffordGold ? <em>Not enough Gold.</em> : !canAffordMaterials ? <em>Need {upgrade.materialCost} Materials. Current stock: {materialStock}.</em> : null}</div></div><div className={styles.actions}><button type="button" className={styles.buyButton} disabled={owned || !canAffordGold || !canAffordMaterials || !prerequisiteMet} onClick={() => onBuyUpgrade(upgrade.upgradeId)}>{owned ? "Installed" : "Install"}</button></div></div></article>; }

function TrainingRewardModal({ reward, onClose }: { reward: TrainingRewardSummary; onClose: () => void }) { const statLine = reward.statKey ? reward.statSucceeded ? `${reward.statKey}: Grade ${reward.gradeBefore} → ${reward.gradeAfter}, stat ${reward.statBefore} → ${reward.statAfter}` : `${reward.statKey}: no increase this time` : "No stat roll for this focus"; return <div className={styles.modalBackdrop} role="presentation" onClick={onClose}><section className={styles.detailModal} role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><button type="button" className={styles.closeButton} onClick={onClose}>×</button><div style={{ display: "grid", gridTemplateColumns: "72px minmax(0,1fr)", gap: 14, alignItems: "center", marginBottom: 12 }}><img src={reward.statKey ? ICONS.stat : ICONS.xp} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} style={{ width: 72, height: 72, objectFit: "cover", borderRadius: 14, border: "1px solid rgba(245,201,128,.4)" }} /><div><p className={styles.kicker}>Training Complete</p><h2 style={{ margin: 0 }}>{reward.creatureName} — {reward.focusName}</h2><p style={{ margin: "6px 0 0", color: "#fff0c9", fontWeight: 900 }}>{reward.leveled ? "Level up!" : reward.statSucceeded ? "Stat coaching succeeded." : "Training report ready."}</p></div></div><div className={styles.statsGrid}><article className={styles.statBox}><span>XP</span><strong>{xpText(reward)}</strong></article><article className={styles.statBox}><span>Level</span><strong>{reward.levelBefore} → {reward.levelAfter}</strong></article>{reward.statKey ? <article className={styles.statBox}><span>Stat Result</span><strong>{statLine}</strong></article> : null}{typeof reward.statRoll === "number" ? <article className={styles.statBox}><span>Roll</span><strong>{reward.statRoll}/100 vs {reward.statChance}%</strong></article> : null}</div><div style={{ marginTop: 12, display: "grid", gap: 8 }}>{reward.notes.map((note) => <p key={note} className={styles.gradePreview} style={{ margin: 0 }}>{note}</p>)}</div><div className={styles.actions} style={{ marginTop: 14 }}><button type="button" className={styles.buyButton} onClick={onClose}>Close Report</button></div></section></div>; }


