"use client";

import { useMemo, useState } from "react";
import { RHEA_FLINT, TRAINING_FOCI, getTrainingCreatureLabel, getTrainingCount } from "@/data/trainingGrounds";
import { getVariantDefinition } from "@/data/creatures";
import { formatGold } from "@/lib/formatters";
import { useGameContext } from "@/state/GameProvider";
import type { CreatureRecord } from "@/types/creature";
import type { CreatureId } from "@/types/ids";
import type { TrainingFocus, TrainingFocusId } from "@/data/trainingGrounds";
import styles from "@/features/market/MarketScreen.module.css";

const ICONS = { grounds: "/images/buildings/town/training_grounds_interior.png", rhea: RHEA_FLINT.portraitPath, whistle: "/images/ui/icons/icon_training_whistle.png", price: "/images/ui/icons/icon_price_tag.png", energy: "/images/ui/icons/icon_energy.png" } as const;
const RHEA_GREETING = "Pick a creature and a focus. Short sessions, clean notes, no miracle promises. Good training is repeatable.";
type TrainingMode = "interior" | "train" | "talk" | "records";

function getPanelStyle() { return { position: "relative", zIndex: 3, padding: 18, border: "1px solid rgba(245,201,128,.55)", borderRadius: 4, background: "rgba(21, 10, 5, .72)", color: "#fff0c9", boxShadow: "0 14px 34px rgba(0,0,0,.42)", backdropFilter: "blur(2px)" } as const; }
function getInteriorButtonStyle() { return { display: "grid", gap: 4, justifyItems: "center", minWidth: 220, padding: "18px 20px", border: "2px solid rgba(245,201,128,.72)", borderRadius: 4, background: "rgba(0,0,0,.42)", color: "#fff7dd", boxShadow: "0 14px 28px rgba(0,0,0,.35)", cursor: "pointer" } as const; }
function getCreatureImage(creature: CreatureRecord): string { return getVariantDefinition(creature.variantId).portraitPath; }
function getBestStatLabel(creature: CreatureRecord): string { const order = ["D", "C", "B", "A", "S"]; const best = Object.entries(creature.statGrades).sort((a, b) => order.indexOf(b[1]) - order.indexOf(a[1]))[0]; return best ? `${best[0]} ${best[1]}` : "No stat grades"; }

export function TrainingGroundsScreen() {
  const { currentSave, goToMainMenu, goToTown, saveCurrentGame, trainCreature } = useGameContext();
  const [message, setMessage] = useState(RHEA_GREETING);
  const [trainingMode, setTrainingMode] = useState<TrainingMode>("interior");
  const [selectedCreatureId, setSelectedCreatureId] = useState<CreatureId | null>(null);
  const creatures = useMemo(() => currentSave?.creatures ?? [], [currentSave]);
  const selectedCreature = useMemo(() => creatures.find((creature) => creature.creatureId === selectedCreatureId) ?? creatures[0] ?? null, [creatures, selectedCreatureId]);

  if (!currentSave) return <main className={styles.emptyScreen}><section className={styles.emptyPanel}><h1>No active save</h1><p>Load or create a save before entering the Training Grounds.</p><button type="button" onClick={goToMainMenu}>Return to Main Menu</button></section></main>;

  function runTraining(focusId: TrainingFocusId) { if (!selectedCreature) return; const result = trainCreature(selectedCreature.creatureId, focusId); if (result.ok) saveCurrentGame(result.save); setMessage(result.message); setTrainingMode("train"); }
  function openTalk() { setMessage("Rhea folds her arms. 'The best creature is not always the rarest one. It is the one you trained for the job you actually need done.'"); setTrainingMode("talk"); }

  return <main className={styles.screen}><section className={styles.frame}><div className={styles.backgroundArt} aria-hidden="true" /><div className={styles.shade} aria-hidden="true" /><header className={styles.header}><div><p className={styles.kicker}>M45 Training Grounds</p><h1>Training Grounds</h1><p>{RHEA_FLINT.name}, {RHEA_FLINT.title}, runs creature improvement drills for ranch work, breeding prep, and future combat readiness.</p><p className={styles.message}>{message}</p></div><div className={styles.headerActions}><div className={styles.statBox}><span>Gold</span><strong>{formatGold(currentSave.currencies.gold)}</strong></div><div className={styles.statBox}><span>Creatures</span><strong>{creatures.length}</strong></div><button type="button" className={styles.backButton} onClick={goToTown}>Back to Town</button><button type="button" className={styles.backButton} onClick={goToMainMenu}>Main Menu</button></div></header>{trainingMode === "interior" ? <TrainingInterior creatureCount={creatures.length} onTalk={openTalk} onTrain={() => setTrainingMode("train")} onRecords={() => setTrainingMode("records")} /> : null}{trainingMode === "talk" ? <RheaTalkPanel onBack={() => setTrainingMode("interior")} onTrain={() => setTrainingMode("train")} /> : null}{trainingMode === "records" ? <TrainingRecordsPanel creatures={creatures} save={currentSave} onBack={() => setTrainingMode("interior")} onTrain={() => setTrainingMode("train")} /> : null}{trainingMode === "train" ? <TrainingPanel save={currentSave} creatures={creatures} selectedCreature={selectedCreature} setSelectedCreatureId={setSelectedCreatureId} onTrain={runTraining} onBack={() => setTrainingMode("interior")} /> : null}</section></main>;
}

function TrainingInterior({ creatureCount, onTalk, onTrain, onRecords }: { creatureCount: number; onTalk: () => void; onTrain: () => void; onRecords: () => void }) {
  return <section aria-label="Training Grounds interior" style={{ position: "relative", zIndex: 2, minHeight: "calc(100vh - 230px)", padding: "28px 34px 34px", overflow: "hidden" }}><div aria-hidden="true" style={{ position: "absolute", inset: 0, background: `linear-gradient(180deg, rgba(0,0,0,.10), rgba(0,0,0,.58)), url(${ICONS.grounds}) center/cover`, opacity: .44 }} /><div style={{ position: "relative", zIndex: 3, display: "grid", gridTemplateColumns: "minmax(260px, 360px) minmax(0, 1fr)", gap: 26, alignItems: "end", minHeight: "58vh" }}><aside style={getPanelStyle()}><div style={{ display: "grid", gridTemplateColumns: "76px minmax(0,1fr)", gap: 12, alignItems: "center" }}><img src={ICONS.rhea} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} style={{ width: 76, height: 76, objectFit: "cover", borderRadius: 999, border: "1px solid rgba(245,201,128,.55)" }} /><div><p className={styles.kicker}>Coach</p><h2 style={{ margin: 0 }}>Rhea Flint</h2><p style={{ margin: "6px 0 0" }}>{creatureCount} creatures available</p></div></div><p style={{ marginTop: 16, lineHeight: 1.55 }}>{RHEA_GREETING}</p><div style={{ display: "grid", gap: 8 }}><button type="button" className={styles.buyButton} onClick={onTalk}>Talk to Rhea</button><button type="button" className={styles.buyButton} onClick={onTrain}>Start Training</button><button type="button" className={styles.buyButton} onClick={onRecords}>Training Records</button></div></aside><div style={{ position: "relative", minHeight: 430 }}><button type="button" style={{ ...getInteriorButtonStyle(), position: "absolute", left: "10%", top: "38%" }} onClick={onTrain}><img src={ICONS.whistle} alt="" style={{ width: 58, height: 58, objectFit: "cover", borderRadius: 999 }} /><strong>Training Yard</strong><span style={{ color: "#7fdbff", fontWeight: 900 }}>XP • Stats • Prep</span></button><button type="button" style={{ ...getInteriorButtonStyle(), position: "absolute", right: "7%", top: "31%" }} onClick={onTalk}><img src={ICONS.rhea} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} style={{ width: 66, height: 66, objectFit: "cover", borderRadius: 999 }} /><strong>Rhea Flint</strong><span style={{ color: "#7fdbff", fontWeight: 900 }}>Talk • Advice</span></button><button type="button" style={{ ...getInteriorButtonStyle(), position: "absolute", left: "39%", bottom: "8%" }} onClick={onRecords}><img src={ICONS.energy} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} style={{ width: 58, height: 58, objectFit: "cover", borderRadius: 999 }} /><strong>Records Bench</strong><span style={{ color: "#7fdbff", fontWeight: 900 }}>Session counts</span></button></div></div></section>;
}

function RheaTalkPanel({ onBack, onTrain }: { onBack: () => void; onTrain: () => void }) { return <section style={{ position: "relative", zIndex: 3, padding: 24, display: "grid", gridTemplateColumns: "320px minmax(0, 1fr)", gap: 18 }}><aside style={getPanelStyle()}><img src={ICONS.rhea} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} style={{ width: "100%", maxHeight: 280, objectFit: "cover", borderRadius: 8, border: "1px solid rgba(245,201,128,.45)" }} /><h2>Rhea Flint</h2><p>{RHEA_FLINT.title}</p></aside><section style={getPanelStyle()}><p className={styles.kicker}>Conversation</p><h2>Useful Strength</h2><p style={{ fontSize: "1.05rem", lineHeight: 1.65 }}>"Combat matters eventually, sure. But a creature that can haul, focus, bond, recover, and follow a plan is useful every day. We start there."</p><p style={{ lineHeight: 1.6 }}>Rhea's first drills are intentionally simple: XP, stat coaching, chore prep, and breeding fitness. Later she can support move loadouts, advanced tutors, and combat roles.</p><div style={{ display: "flex", flexWrap: "wrap", gap: 10 }}><button type="button" className={styles.buyButton} onClick={onTrain}>Start Training</button><button type="button" className={styles.backButton} onClick={onBack}>Back to Grounds</button></div></section></section>; }

function TrainingRecordsPanel({ creatures, save, onBack, onTrain }: { creatures: CreatureRecord[]; save: NonNullable<ReturnType<typeof useGameContext>["currentSave"]>; onBack: () => void; onTrain: () => void }) { return <section style={{ position: "relative", zIndex: 3, padding: 24, display: "grid", gridTemplateColumns: "320px minmax(0, 1fr)", gap: 18 }}><aside style={getPanelStyle()}><h2>Training Records</h2><p>Session counts are stored per creature and focus.</p><button type="button" className={styles.buyButton} onClick={onTrain}>Start Training</button><button type="button" className={styles.backButton} onClick={onBack}>Back to Grounds</button></aside><section style={getPanelStyle()}><h2>Recent Focus Counts</h2><div className={styles.listings}>{creatures.map((creature) => <article key={creature.creatureId} className={styles.listing}><div className={styles.listingArt}><img src={getCreatureImage(creature)} alt="" /></div><div className={styles.listingBody}><h3 className={styles.listingName}>{creature.nickname}</h3><p className={styles.listingDesc}>{getTrainingCreatureLabel(creature)}</p><p className={styles.gradePreview}>{TRAINING_FOCI.map((focus) => `${focus.name}: ${getTrainingCount(save, creature.creatureId, focus.focusId)}`).join(" • ")}</p></div></article>)}</div></section></section>; }

function TrainingPanel({ save, creatures, selectedCreature, setSelectedCreatureId, onTrain, onBack }: { save: NonNullable<ReturnType<typeof useGameContext>["currentSave"]>; creatures: CreatureRecord[]; selectedCreature: CreatureRecord | null; setSelectedCreatureId: (id: CreatureId) => void; onTrain: (focusId: TrainingFocusId) => void; onBack: () => void }) {
  return <section className={styles.grid} style={{ position: "relative", zIndex: 3, padding: "14px 18px 24px" }}><aside className={styles.panel}><h2>Select Creature</h2><div className={styles.sideList}>{creatures.map((creature) => <button key={creature.creatureId} type="button" className={styles.infoCard} onClick={() => setSelectedCreatureId(creature.creatureId)}><img src={getCreatureImage(creature)} alt="" /><span>{getVariantDefinition(creature.variantId).name}</span><strong>{getTrainingCreatureLabel(creature)}</strong></button>)}<button type="button" className={styles.backButton} onClick={onBack}>Back to Grounds</button></div></aside><section className={styles.panel}><h2>{selectedCreature ? `${selectedCreature.nickname}'s Training` : "No Creature Selected"}</h2>{selectedCreature ? <article className={styles.listing}><div className={styles.listingArt}><img src={getCreatureImage(selectedCreature)} alt="" /></div><div className={styles.listingBody}><span className={styles.listingMeta}>{getVariantDefinition(selectedCreature.variantId).family} • {getVariantDefinition(selectedCreature.variantId).rarity}</span><h3 className={styles.listingName}>{getTrainingCreatureLabel(selectedCreature)}</h3><p className={styles.listingDesc}>Best stat: {getBestStatLabel(selectedCreature)} • Affection {selectedCreature.affection}/100</p><p className={styles.gradePreview}>Choose one focus. Training costs Gold and creature Energy, but does not advance the day.</p></div></article> : null}<div className={styles.listings}>{TRAINING_FOCI.map((focus) => <TrainingFocusCard key={focus.focusId} save={save} creature={selectedCreature} focus={focus} onTrain={onTrain} />)}</div></section></section>;
}

function TrainingFocusCard({ save, creature, focus, onTrain }: { save: NonNullable<ReturnType<typeof useGameContext>["currentSave"]>; creature: CreatureRecord | null; focus: TrainingFocus; onTrain: (focusId: TrainingFocusId) => void }) { const canAfford = save.currencies.gold >= focus.costGold; const hasEnergy = Boolean(creature && creature.energy >= focus.energyCost); return <article className={styles.listing}><div className={styles.listingArt}><img src={focus.iconPath} alt="" onError={(event) => { event.currentTarget.src = ICONS.whistle; }} /></div><div className={styles.listingBody}><span className={styles.listingMeta}>{focus.category} • {focus.energyCost} Energy</span><h3 className={styles.listingName}>{focus.name}</h3><p className={styles.listingDesc}>{focus.description}</p><p className={styles.gradePreview}>{focus.effectLabel}</p><div className={styles.price}><img src={ICONS.price} alt="" /><div><span>Cost</span><strong>{formatGold(focus.costGold)}</strong>{creature ? <em>Used {getTrainingCount(save, creature.creatureId, focus.focusId)} time(s) for this creature.</em> : null}</div></div><div className={styles.actions}><button type="button" className={styles.buyButton} disabled={!creature || !canAfford || !hasEnergy} onClick={() => onTrain(focus.focusId)}>Train</button></div></div></article>; }
