"use client";
import { useState, type ReactNode } from "react";
import { useGameContext } from "@/state/GameProvider";
import { useNavigation } from "@/features/navigation/NavigationContext";
import { GameDialog } from "@/features/ui/GameDialog";
import { getVariantDefinition, STAT_KEYS } from "@/data/creatures";
import { BATTLE_OUTFITTER_ITEMS, EQUIPMENT_SLOTS, EQUIPMENT_SLOT_LABELS, getEquipmentSlots, getBattleReadinessLabel } from "@/data/battleOutfitter";
import type { ColiseumC4CarryoverMap } from "@/data/coliseumC4";
import type { CreatureRecord } from "@/types/creature";
import type { CreatureId } from "@/types/ids";
import { TeamLoadoutPanel } from "@/features/battle-outfitter/TeamLoadoutPanel";
import s from "./ColiseumCourtyard.module.css";
type Enemy = { name:string; variantName:string; level:number; role:string; equipment:string; moves:string[] };
export function ColiseumTeamStaging({title,roster,selected,onChange,onReturn,onStart,unavailable,enemyPreview,opponent,strategy,locked=false,carryover,tacticsStock,armed,onArm,rules,message}: {
 title:string; roster:CreatureRecord[];selected:CreatureId[];onChange:(ids:CreatureId[])=>void;onReturn:()=>void;onStart:()=>void;unavailable:(creature:CreatureRecord)=>string|null;enemyPreview:Enemy[];opponent:string;strategy:string;locked?:boolean;carryover?:ColiseumC4CarryoverMap;tacticsStock:number;armed:boolean;onArm:()=>void;rules:ReactNode;message:string;
}){
 const {currentSave:save,goToBattleOutfitter}=useGameContext();const {open}=useNavigation();
 const [popup,setPopup]=useState<"roster"|"opponent"|"rules"|"prep"|"profile"|"gear"|null>(null);
 const [slot,setSlot]=useState(0),[page,setPage]=useState(0),[profileId,setProfileId]=useState<CreatureId|null>(null);
 if(!save)return null;
 const team=selected.map(id=>roster.find(c=>c.creatureId===id)).filter((c):c is CreatureRecord=>!!c);
 const pages=Math.max(1,Math.ceil(roster.length/4)),currentPage=Math.min(page,pages-1);
 const profile=roster.find(c=>c.creatureId===profileId);
 const canStart=team.length===3&&team.every(c=>!unavailable(c))&&(!armed||tacticsStock>0);
 function choose(c:CreatureRecord,targetSlot=slot){if(locked||unavailable(c))return;const ids=[...selected];const existing=ids.indexOf(c.creatureId);if(existing!==-1){if(targetSlot<ids.length){[ids[targetSlot],ids[existing]]=[ids[existing],ids[targetSlot]];}}else if(targetSlot<ids.length)ids[targetSlot]=c.creatureId;else ids.push(c.creatureId);onChange(ids);setPopup(null);}
 function change(ix:number){setSlot(ix);setPopup("roster");}
 const gearCount=(c:CreatureRecord)=>Object.values(getEquipmentSlots(save,c.creatureId)).filter(Boolean).length;
 const prep=<><h2>Your Team · {team.length} / 3</h2><p>{locked?"Roster locked for this run.":"Choose three available creatures."}</p><p className={s.muted}>Select a teammate’s Gear button to compare, buy or equip. Gear is optional.</p><button onClick={()=>setPopup("prep")}>Team preparation</button><button aria-pressed={armed} disabled={tacticsStock===0&&!armed} onClick={onArm}>Tactics Kit · {armed?"On":"Off"} ({tacticsStock})</button><p className={s.muted}>Consumed when battle starts.</p><button className={s.primary} disabled={!canStart} onClick={onStart}>Enter Battle</button></>;
 return <main className={s.courtyard} data-coliseum="team"><header className={s.header}><div><button onClick={onReturn}>‹ Back</button></div><h1>{title}</h1><div><button onClick={()=>open("menu")} data-navigation-launcher>Menu</button></div></header><section className={`${s.layout} ${s.team}`}><aside className={s.panel}><h2>Opponent</h2><p>{opponent}</p><p className={s.desktop}>{strategy}</p><button onClick={()=>setPopup("opponent")}>View team</button><button onClick={()=>setPopup("rules")}>Rules</button></aside><section className={s.stage} aria-label="Selected full-body team">{[0,1,2].map(ix=>{const c=team[ix],v=c?getVariantDefinition(c.variantId):null;return <article className={s.creature} key={ix} data-team-slot={ix+1}><div className={s.body}>{c&&v?<img src={v.profilePath||v.portraitPath} alt={`${c.nickname}, full body`}/>:<span className={s.wood}>Slot {ix+1}</span>}</div><div className={s.plinth}><span className={s.slotNumber}>TEAM {ix+1}</span>{c?.nickname??"Choose creature"}<small>{c?unavailable(c)?"Unavailable":carryover?.[c.creatureId]?`HP ${Math.round(carryover[c.creatureId].hpRatio*100)}% · BE ${Math.round(carryover[c.creatureId].battleEnergyRatio*100)}%`:`Level ${c.level} · ${gearCount(c)}/5 gear`:"Empty"}</small></div><div className={s.slotActions}><button disabled={locked||ix>team.length} onClick={()=>change(ix)}>{locked?"Locked":"Change"}</button>{c&&<button aria-label={`Gear for ${c.nickname}`} onClick={()=>{setProfileId(c.creatureId);setPopup("gear");}}>Gear · {gearCount(c)}/5</button>}</div></article>;})}</section><aside className={s.panel}>{prep}<button onClick={()=>setPopup("opponent")}>Opponent & Rules</button></aside><div className={s.mobileActions}><button onClick={()=>setPopup("opponent")}>Opponent</button><button onClick={()=>setPopup("prep")}>Prep · {team.length}/3</button><button className={s.primary} disabled={!canStart} onClick={onStart}>Enter Battle</button></div></section><nav className={s.roster} aria-label="Creature roster"><button aria-label="Previous creatures" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>‹</button>{roster.slice(currentPage*4,currentPage*4+4).map(c=><button key={c.creatureId} aria-label={`Inspect ${c.nickname}`} aria-pressed={selected.includes(c.creatureId)} onClick={()=>{setProfileId(c.creatureId);setPopup("profile");}}><img src={c.portraitPath||getVariantDefinition(c.variantId).portraitPath} alt=""/><span>{c.nickname}</span></button>)}<span className={s.wood}>{currentPage+1}/{pages}</span><button aria-label="Next creatures" disabled={currentPage===pages-1} onClick={()=>setPage(currentPage+1)}>›</button></nav>
 {popup==="roster"&&<GameDialog title={`Choose creature · Slot ${slot+1}`} onClose={()=>setPopup(null)} wide><p>Choosing a teammate already selected swaps their position.</p><div className={s.dialogGrid}>{roster.map(c=><article key={c.creatureId}><img src={c.portraitPath||getVariantDefinition(c.variantId).portraitPath} alt=""/><h3>{c.nickname} · Level {c.level}</h3><p>{unavailable(c)||getBattleReadinessLabel(save,c.creatureId)}</p><button disabled={locked||!!unavailable(c)} onClick={()=>choose(c)}>Choose {c.nickname}</button></article>)}</div>{selected[slot]&&<button onClick={()=>{onChange(selected.filter((_,ix)=>ix!==slot));setPopup(null);}}>Clear Slot {slot+1}</button>}</GameDialog>}
 {popup==="opponent"&&<GameDialog title="Opponent & Rules" onClose={()=>setPopup(null)} wide><h3>{opponent}</h3><p>{strategy}</p><div className={s.dialogGrid}>{enemyPreview.map(e=><article key={e.name}><h3>{e.name}</h3><p>Level {e.level} · {e.variantName} · {e.role}</p><p>{e.equipment}</p><p>{e.moves.join(" · ")}</p></article>)}</div>{rules}</GameDialog>}
 {popup==="rules"&&<GameDialog title="Battle Rules" onClose={()=>setPopup(null)}>{rules}</GameDialog>}
 {popup==="prep"&&<GameDialog title="Team Preparation" onClose={()=>setPopup(null)} wide><p role="status">{message}</p>{team.map(c=><section key={c.creatureId}><h3>{c.nickname}</h3><p>{unavailable(c)||`${gearCount(c)}/5 equipment slots filled · Gear is optional`}</p><button onClick={()=>{setProfileId(c.creatureId);setPopup("gear");}}>Manage {c.nickname}’s gear</button><dl>{EQUIPMENT_SLOTS.map(key=>{const id=getEquipmentSlots(save,c.creatureId)[key];return <div key={key}><dt>{EQUIPMENT_SLOT_LABELS[key]}</dt><dd>{BATTLE_OUTFITTER_ITEMS.find(i=>i.itemId===id)?.name??"Empty"}</dd></div>;})}</dl></section>)}<p>Equipment changes numeric battle stats only. Innate grades remain unchanged.</p><button onClick={goToBattleOutfitter}>Visit Outfitter</button><p>Returning from the Outfitter starts a new team selection. Active gauntlet teams remain locked.</p><button aria-pressed={armed} disabled={tacticsStock===0&&!armed} onClick={onArm}>Tactics Kit · {armed?"On":"Off"} ({tacticsStock})</button><p>Consumed only when battle starts. Gives the team Inspired for one round and +10 current and maximum Battle Energy.</p>{rules}<button disabled={!canStart} onClick={onStart}>Enter Battle</button></GameDialog>}
 {popup==="gear"&&profile&&<GameDialog title={`${profile.nickname} · Loadout`} onClose={()=>setPopup(null)} wide><TeamLoadoutPanel key={profile.creatureId} creature={profile} blocked={locked?"Equipment is locked for this gauntlet run.":unavailable(profile)}/></GameDialog>}
 {popup==="profile"&&profile&&<GameDialog title={`${profile.nickname} · Profile`} onClose={()=>setPopup(null)}><p>{getVariantDefinition(profile.variantId).name} · Level {profile.level}</p><p>{unavailable(profile)||getBattleReadinessLabel(save,profile.creatureId)}</p><p>Base numbers · Innate grades</p><dl className={s.stats}>{STAT_KEYS.map(key=><div key={key}><dt>{key}</dt><dd>{profile.stats[key]}<b>{profile.statGrades[key]}</b></dd></div>)}</dl>{carryover?.[profile.creatureId]&&<p>Saved gauntlet condition: HP {Math.round(carryover[profile.creatureId].hpRatio*100)}% · Battle Energy {Math.round(carryover[profile.creatureId].battleEnergyRatio*100)}%.</p>}<button onClick={()=>setPopup("prep")}>Team loadouts</button>{!locked&&<div className={s.actions}>{[0,1,2].map(ix=><button key={ix} disabled={!!unavailable(profile)||ix>selected.length} onClick={()=>choose(profile,ix)}>Choose for slot {ix+1}</button>)}</div>}</GameDialog>}
 </main>;
}
