"use client";
import { useState } from "react";
import { useGameContext } from "@/state/GameProvider";
import { useNavigation } from "@/features/navigation/NavigationContext";
import { GameDialog } from "@/features/ui/GameDialog";
import { COLISEUM_C2_ENCOUNTERS, getColiseumC2Access, getColiseumC2Progress, getColiseumCreatureBattleRecord, getColiseumC2RewardLabel, getColiseumRepeatPoolLabel, recordColiseumC2BattleResult, type ColiseumC2EncounterDefinition } from "@/data/coliseumC2";
import { getColiseumC3State, syncColiseumC3Rewards } from "@/data/coliseumC3";
import { getColiseumC4State, getColiseumC4Summary, getColiseumC4DailyChallenge, getColiseumC4Gauntlets, getColiseumC4WeeklyBoss, getColiseumC4Access, getColiseumC4Modifier, getColiseumC4ChallengeByKey, buildColiseumC4Encounter, recordColiseumC4BattleResult, abandonColiseumC4Run, type ColiseumC4ChallengeDefinition } from "@/data/coliseumC4";
import { ColiseumBattle } from "./ColiseumC2Screen";
import { ColiseumC4Battle } from "./ColiseumC4Battle";
import { ColiseumProgressionScreen as Exchange } from "./ColiseumProgressionShellC3";
import s from "./ColiseumCourtyard.module.css";
const modes = [["circuit","Circuit"],["daily","Daily"],["gauntlets","Gauntlets"],["boss","Boss Trial"],["exchange","Exchange"]] as const;
type Mode = typeof modes[number][0];
const art = "/images/ui/coliseum-v1/";
const words = (v:string) => v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export function ColiseumCourtyard() {
 const { currentSave:save, saveCurrentGame, goToTown, goToBattleOutfitter } = useGameContext();
 const { open } = useNavigation();
 const [mode,setMode]=useState<Mode>("circuit"); const [index,setIndex]=useState(0);
 const [popup,setPopup]=useState<"rules"|"records"|"exchange"|"abandon"|"report"|null>(null);
 const [report,setReport]=useState("");
 const [battle,setBattle]=useState<ColiseumC2EncounterDefinition|null>(null);
 const [challengeBattle,setChallengeBattle]=useState<ColiseumC4ChallengeDefinition|null>(null);
 if(!save) return null;
 const progress=getColiseumC2Progress(save), state=getColiseumC4State(save), summary=getColiseumC4Summary(save);
 const active=state.activeRun?getColiseumC4ChallengeByKey(save,state.activeRun.challengeKey):null;
 const challenges=mode==="daily"?[getColiseumC4DailyChallenge(save)]:mode==="boss"?[getColiseumC4WeeklyBoss(save)]:getColiseumC4Gauntlets(save);
 const items=mode==="circuit"?COLISEUM_C2_ENCOUNTERS:challenges;
 const selectedIndex=Math.min(index,items.length-1), item=items[selectedIndex];
 const encounter=mode==="circuit"?item as ColiseumC2EncounterDefinition:null;
 const challenge=encounter?null:item as ColiseumC4ChallengeDefinition;
 const access=encounter?getColiseumC2Access(save,encounter):getColiseumC4Access(save,challenge!);
 const stage=challenge && state.activeRun?.challengeKey===challenge.challengeKey?state.activeRun.stageIndex:undefined;
 const claimed=challenge?(challenge.mode==="daily"?state.dailyClaimKeys:challenge.mode==="boss"?state.weeklyBossClaimKeys:state.weeklyGauntletClaimKeys).includes(challenge.claimKey):false;
 const reward=encounter?(progress.completedEncounterIds.includes(encounter.encounterId)?"Repeat purse · see rewards":getColiseumC2RewardLabel(encounter.firstClearReward)):claimed?(challenge?.mode==="gauntlet"?"Reduced repeat reward":"Primary reward claimed · XP still earned"):`${challenge!.reward.marks} Marks · ${challenge!.reward.materials} Materials`;
 function enter(){if(!access.unlocked)return;if(encounter)setBattle(encounter);else setChallengeBattle(challenge);}
 function showReport(message:string){setReport(message.replaceAll("C4 ",""));setPopup("report");}
 if(battle) return <ColiseumBattle encounter={battle} onReturn={()=>setBattle(null)} onComplete={(outcome,rounds,ids,performance,resultId)=>{const result=recordColiseumC2BattleResult(save,battle.encounterId,outcome,rounds,ids,performance,resultId);if(!result.duplicate)saveCurrentGame(syncColiseumC3Rewards(result.save).save);setBattle(null);showReport(result.message);}}/>;
 if(challengeBattle){const ix=state.activeRun?.challengeKey===challengeBattle.challengeKey?state.activeRun.stageIndex:0;const run=state.activeRun?.challengeKey===challengeBattle.challengeKey?state.activeRun:null;return <ColiseumC4Battle key={`${challengeBattle.challengeKey}_${ix}`} challenge={challengeBattle} stageIndex={ix} encounter={buildColiseumC4Encounter(challengeBattle,ix)} lockedTeamCreatureIds={run?.teamCreatureIds} carryover={run?.carryover} onReturn={()=>setChallengeBattle(null)} onComplete={(outcome,rounds,ids,performance,resultId,finalState)=>{const result=recordColiseumC4BattleResult(save,challengeBattle,ix,outcome,rounds,ids,performance,resultId,finalState);if(result.changed)saveCurrentGame(result.save);setChallengeBattle(null);showReport(result.message);}}/>;}
 const page=Math.floor(selectedIndex/3), pages=Math.ceil(items.length/3);
 const brief=<><h2>Challenge Brief</h2><p className={s.desktop}>{encounter?encounter.strategyLabel:challenge!.modifierIds.map(id=>getColiseumC4Modifier(id).name).join(" · ")}</p><p>{reward}</p><p className={s.desktop}>{challenge?.mode==="gauntlet"?"Same team for all stages. Rewards after the final victory.":encounter?`Recommended level ${encounter.recommendedLevel}`:challenge?.mode==="daily"?"Changes with the next Ranch Day.":"Changes with the next Ranch Week."}</p>{!access.unlocked&&<p className={s.desktop}>{access.reason}</p>}<button onClick={()=>setPopup("rules")}>Rules & Rewards{!access.unlocked?" · Locked":""}</button><button className={s.primary} disabled={!access.unlocked} onClick={enter}>{stage!==undefined?`Continue Stage ${stage+1}`:"Choose Team"}</button></>;
 return <main className={s.courtyard} data-coliseum="entrance"><header className={s.header}><div><button onClick={goToTown}>‹ Town</button></div><h1>Coliseum</h1><div><span className={s.marks}>Marks {getColiseumC3State(save).marks}</span><button onClick={()=>open("menu")} data-navigation-launcher>Menu</button></div></header><section className={s.layout}><aside className={s.panel}><h2>{modes.find(x=>x[0]===mode)?.[1]}</h2><div className={s.choices}>{items.slice(page*3,page*3+3).map((entry,i)=><button key={entry.name} className={s.choice} aria-pressed={selectedIndex===page*3+i} onClick={()=>setIndex(page*3+i)}><img src={art+mode+".webp"} alt=""/><span>{entry.name}<small>{"recommendedLevel" in entry?`Level ${entry.recommendedLevel}`:`${entry.encounterIds.length} stage${entry.encounterIds.length>1?"s":""}`}</small></span></button>)}</div>{pages>1&&<div className={s.pager}><button aria-label="Previous encounters" disabled={page===0} onClick={()=>setIndex((page-1)*3)}>‹</button><span>{page+1} / {pages}</span><button aria-label="Next encounters" disabled={page===pages-1} onClick={()=>setIndex((page+1)*3)}>›</button></div>}<div className={s.actions}><button onClick={()=>setPopup("records")}>Records</button><button onClick={goToBattleOutfitter}>Outfitter</button></div>{active&&<button className={s.primary} onClick={()=>setChallengeBattle(active)}>Resume · Stage {state.activeRun!.stageIndex+1}</button>}</aside><section className={s.sign}><h2 className={s.wood}>{item.name}</h2><p>{encounter?"Permanent Circuit":`${challenge!.encounterIds.length} stage${challenge!.encounterIds.length>1?"s":""}`}</p></section><aside className={s.panel}>{brief}</aside></section><nav className={s.dock} aria-label="Coliseum modes">{modes.map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>{if(id==="exchange")setPopup("exchange");else{setMode(id);setIndex(0);}}}><img src={art+id+".webp"} alt=""/><span>{label}</span></button>)}</nav>
 {popup==="rules"&&<GameDialog title={`${item.name} · Rules & Rewards`} onClose={()=>setPopup(null)}><p>{item.description}</p>{!access.unlocked&&<p className={s.status}>{access.reason}</p>}{encounter?<><p>Recommended level {encounter.recommendedLevel}. {encounter.strategyLabel}</p><h3>First clear</h3><p>{getColiseumC2RewardLabel(encounter.firstClearReward)}</p><h3>Repeat purse</h3><p>{getColiseumRepeatPoolLabel(encounter)}</p><p>All participants earn Combat XP, including fainted creatures. Overleveled repeats give reduced XP. Marks and combat loot are recorded with the result.</p></>:<><p>{reward}</p>{challenge!.reward.itemId&&<p>{claimed&&challenge!.mode!=="gauntlet"?"Claimed item":"Primary reward item"}: {challenge!.reward.itemQuantity} {words(challenge!.reward.itemId)}</p>}{challenge!.modifierIds.map(id=>{const m=getColiseumC4Modifier(id);return <section key={id}><h3>{m.name}</h3><p>{m.description}</p></section>;})}<p>Enemy levels +{challenge!.levelBonus}. {challenge!.aiDifficultyOverride?words(challenge!.aiDifficultyOverride)+" AI.":"Encounter AI."}</p>{challenge!.mode==="gauntlet"?<p>Three consecutive victories with the same roster. Between stages, living creatures recover 30% maximum HP and 25% maximum Battle Energy; fainted creatures return at 15% HP. Statuses and cooldowns clear. Defeat or a draw ends the run. First weekly clear grants full rewards; repeat clears give approximately 35% Marks and one Material.</p>:<p>Primary rewards are available once per Ranch {challenge!.mode==="daily"?"Day":"Week"}. Practice rematches still grant XP and records.</p>}</>}<button disabled={!access.unlocked} onClick={()=>{setPopup(null);enter();}}>Choose Team</button></GameDialog>}
 {popup==="records"&&<GameDialog title="Coliseum Records" onClose={()=>setPopup(null)} wide><p>Marks: {getColiseumC3State(save).marks} · Circuit: {progress.totalWins} wins / {progress.totalLosses} losses / {progress.totalDraws} draws</p><p>Weekly personal score: {summary.weeklyScore} · {summary.weeklyClears} clears. Scores belong to this save.</p>{active&&<section><h3>{active.name} · Stage {state.activeRun!.stageIndex+1}</h3><button onClick={()=>{setPopup(null);setChallengeBattle(active);}}>Continue Run</button> <button onClick={()=>setPopup("abandon")}>Abandon Gauntlet</button></section>}<h3>Challenge history</h3>{state.history.length?state.history.map(entry=><p key={entry.resultId}>{entry.challengeName} · {words(entry.outcome)} · {entry.rounds} rounds · +{entry.marks} Marks · +{entry.materials} Materials</p>):<p>No challenge results yet.</p>}<h3>Circuit history</h3>{progress.history.length?progress.history.map(entry=><p key={entry.resultId}>{entry.encounterName} · {words(entry.outcome)} · {entry.roundCount} rounds · {getColiseumC2RewardLabel(entry.reward)}</p>):<p>No Circuit results yet.</p>}<h3>Circuit creature records</h3>{(save.creatures??[]).map(c=>{const record=getColiseumCreatureBattleRecord(save,c.creatureId);return record.battles>0?<p key={c.creatureId}>{c.nickname}: {record.wins} wins · {record.totalCombatXp} Combat XP</p>:null;})}<h3>Weekly scores</h3>{Object.values(state.weeklyScores).map(entry=><p key={entry.weekKey}>{words(entry.weekKey)}: {entry.score} · {entry.clears} clears · {entry.bestChallengeName}</p>)}<h3>Creature records</h3>{Object.values(state.creatureRecords).map(entry=><p key={entry.creatureId}>{save.creatures?.find(c=>c.creatureId===entry.creatureId)?.nickname??entry.creatureId}: {entry.wins} wins · {entry.totalCombatXp} XP · best score {entry.bestScore}</p>)}</GameDialog>}
 {popup==="exchange"&&<GameDialog title="Marks Exchange" onClose={()=>setPopup(null)} wide><div className={s.legacy}><Exchange initialMode="exchange" embedded/></div></GameDialog>}
 {popup==="abandon"&&<GameDialog title="Abandon Gauntlet?" onClose={()=>setPopup("records")}><p>End the active run? XP earned in completed stages is kept. You will need to begin again at stage one.</p><button onClick={()=>setPopup("records")}>Keep Run</button> <button onClick={()=>{const result=abandonColiseumC4Run(save);if(result.changed)saveCurrentGame(result.save);showReport(result.message);}}>Confirm Abandon</button></GameDialog>}
 {popup==="report"&&<GameDialog title="Coliseum Report" onClose={()=>setPopup(null)}><p role="status">{report}</p></GameDialog>}
 </main>;
}
