import type { GameSave } from "@/types/save";
import type {
  TownUpgradeDefinition,
  TownUpgradeEffects,
  TownUpgradeId,
  TownUpgradePurchaseResult,
  TownUpgradeState,
} from "@/types/upgrades";

export const DEFAULT_TOWN_UPGRADES: TownUpgradeState = {
  market_listing_capacity: 0,
  market_variant_access: 0,
  market_quality_screening: 0,
  market_reroll_discount: 0,
  guild_contract_slots: 0,
  guild_contract_quality: 0,
  guild_donation_rewards: 0,
};

export const UPGRADE_ASSETS = {
  quartermasterProfile: "/images/npcs/guild/mara_vell_profile.png",
  quartermasterPortrait: "/images/npcs/guild/mara_vell_portrait.png",
  servicePermit: "/images/ui/icons/icon_service_permit.png",
  upgradeArrow: "/images/ui/icons/icon_upgrade_arrow.png",
  guildRank: "/images/ui/icons/icon_guild_rank.png",
  upgradeMarket: "/images/ui/icons/icon_upgrade_market.png",
  upgradeRequestBoard: "/images/ui/icons/icon_upgrade_request_board.png",
  marketCapacity: "/images/ui/icons/icon_market_capacity.png",
  variantAccess: "/images/ui/icons/icon_variant_access.png",
  qualityScreening: "/images/ui/icons/icon_quality_screening.png",
  rerollDiscount: "/images/ui/icons/icon_reroll_discount.png",
  contractSlots: "/images/ui/icons/icon_contract_slots.png",
  contractQuality: "/images/ui/icons/icon_contract_quality.png",
  donationRewards: "/images/ui/icons/icon_donation_rewards.png",
  guildPoints: "/images/ui/icons/icon_guild_points.png",
} as const;

export const TOWN_UPGRADE_DEFINITIONS: TownUpgradeDefinition[] = [
  { upgradeId: "market_listing_capacity", category: "market", name: "Market Display Expansion", description: "Increases the number of weekly creature listings available at the Market Stall.", iconPath: UPGRADE_ASSETS.marketCapacity, maxTier: 4, tiers: [{ tier: 1, costGp: 10, effectLabel: "5 weekly market listings" }, { tier: 2, costGp: 25, effectLabel: "6 weekly market listings" }, { tier: 3, costGp: 50, effectLabel: "7 weekly market listings" }, { tier: 4, costGp: 90, effectLabel: "8 weekly market listings" }] },
  { upgradeId: "market_variant_access", category: "market", name: "Specialist Variant Access", description: "Unlocks a tiny chance for market-eligible variants to appear. Breeding remains the main source of variants.", iconPath: UPGRADE_ASSETS.variantAccess, maxTier: 4, tiers: [{ tier: 1, costGp: 15, effectLabel: "+0.5% variant chance" }, { tier: 2, costGp: 35, effectLabel: "+1% variant chance" }, { tier: 3, costGp: 70, effectLabel: "+1.75% variant chance" }, { tier: 4, costGp: 120, effectLabel: "+2.5% variant chance" }] },
  { upgradeId: "market_quality_screening", category: "market", name: "Quality Screening", description: "Improves stat grade and ability quality odds for creatures generated by the Market Stall.", iconPath: UPGRADE_ASSETS.qualityScreening, maxTier: 4, tiers: [{ tier: 1, costGp: 20, effectLabel: "Slightly better stat grade odds" }, { tier: 2, costGp: 45, effectLabel: "Better chance of extra ability quality" }, { tier: 3, costGp: 85, effectLabel: "Better stat and ability screening" }, { tier: 4, costGp: 150, effectLabel: "Certified premium stock screening" }] },
  { upgradeId: "market_reroll_discount", category: "market", name: "Reroll Discount", description: "Reduces the Gold cost to refresh the Market Stall listings.", iconPath: UPGRADE_ASSETS.rerollDiscount, maxTier: 4, tiers: [{ tier: 1, costGp: 10, effectLabel: "10% cheaper rerolls" }, { tier: 2, costGp: 30, effectLabel: "20% cheaper rerolls" }, { tier: 3, costGp: 65, effectLabel: "30% cheaper rerolls" }, { tier: 4, costGp: 110, effectLabel: "40% cheaper rerolls" }] },
  { upgradeId: "guild_contract_slots", category: "guild", name: "Request Board Expansion", description: "Adds more weekly contracts to the Guild Request Board.", iconPath: UPGRADE_ASSETS.contractSlots, maxTier: 4, tiers: [{ tier: 1, costGp: 10, effectLabel: "7 weekly contracts" }, { tier: 2, costGp: 25, effectLabel: "8 weekly contracts" }, { tier: 3, costGp: 55, effectLabel: "9 weekly contracts" }, { tier: 4, costGp: 100, effectLabel: "10 weekly contracts" }] },
  { upgradeId: "guild_contract_quality", category: "guild", name: "Better Client Notices", description: "Improves the odds of Silver and Gold contracts appearing on the Request Board.", iconPath: UPGRADE_ASSETS.contractQuality, maxTier: 4, tiers: [{ tier: 1, costGp: 20, effectLabel: "More Silver requests" }, { tier: 2, costGp: 45, effectLabel: "More Silver and Gold requests" }, { tier: 3, costGp: 90, effectLabel: "Better Gold request odds" }, { tier: 4, costGp: 160, effectLabel: "Elite patron request access" }] },
  { upgradeId: "guild_donation_rewards", category: "guild", name: "Donation Reward Terms", description: "Improves Gold and Guild Point payouts from completed guild donation contracts.", iconPath: UPGRADE_ASSETS.donationRewards, maxTier: 4, tiers: [{ tier: 1, costGp: 15, effectLabel: "+5% Gold from contracts" }, { tier: 2, costGp: 40, effectLabel: "+10% Gold and bonus GP" }, { tier: 3, costGp: 80, effectLabel: "+15% Gold and bonus GP" }, { tier: 4, costGp: 140, effectLabel: "+20% Gold and stronger GP bonuses" }] },
];

export function getDefaultTownUpgrades(): TownUpgradeState { return { ...DEFAULT_TOWN_UPGRADES }; }
export function getTownUpgrades(save: GameSave): TownUpgradeState { return { ...DEFAULT_TOWN_UPGRADES, ...(save.townUpgrades ?? {}) }; }
export function getTownUpgradeDefinition(upgradeId: TownUpgradeId): TownUpgradeDefinition {
  const definition = TOWN_UPGRADE_DEFINITIONS.find((upgrade) => upgrade.upgradeId === upgradeId);
  if (!definition) throw new Error(`Unknown town upgrade: ${upgradeId}`);
  return definition;
}

export function getTotalTownUpgradeTiers(save: GameSave, category?: "market" | "guild"): number {
  const upgrades = getTownUpgrades(save);
  return TOWN_UPGRADE_DEFINITIONS.filter((definition) => !category || definition.category === category).reduce((total, definition) => total + (upgrades[definition.upgradeId] ?? 0), 0);
}

export function getTownUpgradeEffects(save: GameSave): TownUpgradeEffects {
  const upgrades = getTownUpgrades(save);
  const marketListingTier = upgrades.market_listing_capacity;
  const marketVariantTier = upgrades.market_variant_access;
  const marketQualityTier = upgrades.market_quality_screening;
  const marketRerollTier = upgrades.market_reroll_discount;
  const guildSlotTier = upgrades.guild_contract_slots;
  const guildQualityTier = upgrades.guild_contract_quality;
  const guildRewardTier = upgrades.guild_donation_rewards;
  const marketVariantChanceByTier = [0, 0.005, 0.01, 0.0175, 0.025];
  const rerollDiscountByTier = [0, 0.1, 0.2, 0.3, 0.4];
  const goldRewardMultiplierByTier = [1, 1.05, 1.1, 1.15, 1.2];
  const bonusGpByTier = [0, 0, 1, 1, 2];
  return { marketListingCount: 4 + marketListingTier, marketVariantChance: marketVariantChanceByTier[marketVariantTier] ?? 0, marketQualityTier, marketRerollDiscount: rerollDiscountByTier[marketRerollTier] ?? 0, guildContractCount: 6 + guildSlotTier, guildContractQualityTier: guildQualityTier, guildGoldRewardMultiplier: goldRewardMultiplierByTier[guildRewardTier] ?? 1, guildBonusGp: bonusGpByTier[guildRewardTier] ?? 0 };
}

export function getNextUpgradeTier(definition: TownUpgradeDefinition, currentTier: number) { return definition.tiers.find((tier) => tier.tier === currentTier + 1) ?? null; }

export function purchaseTownUpgrade(save: GameSave, upgradeId: TownUpgradeId): TownUpgradePurchaseResult {
  const upgrades = getTownUpgrades(save);
  const definition = getTownUpgradeDefinition(upgradeId);
  const currentTier = upgrades[upgradeId] ?? 0;
  const nextTier = getNextUpgradeTier(definition, currentTier);
  if (!nextTier) return { save, ok: false, message: `${definition.name} is already maxed.` };
  if (save.currencies.guildPoints < nextTier.costGp) return { save, ok: false, message: `Not enough GP for ${definition.name} Tier ${nextTier.tier}.` };

  const remainingGp = save.currencies.guildPoints - nextTier.costGp;
  const immediateRefreshLabel = definition.category === "market" ? "Market listings refreshed immediately." : "Request board refreshed immediately.";
  return {
    save: {
      ...save,
      updatedAt: new Date().toISOString(),
      currencies: { ...save.currencies, guildPoints: remainingGp },
      townUpgrades: { ...upgrades, [upgradeId]: nextTier.tier },
      market: definition.category === "market" ? undefined : save.market,
      guild: definition.category === "guild" ? undefined : save.guild,
      flags: { ...save.flags, m10GuildQuartermasterUsed: true, m10TownUpgradePurchased: true, m105ImmediateUpgradeRefresh: true },
    },
    ok: true,
    message: `${definition.name} upgraded from Tier ${currentTier} to Tier ${nextTier.tier}. ${nextTier.effectLabel}. ${immediateRefreshLabel}`,
    summary: { upgradeId, upgradeName: definition.name, category: definition.category, oldTier: currentTier, newTier: nextTier.tier, effectLabel: nextTier.effectLabel, costGp: nextTier.costGp, remainingGp, immediateRefreshLabel },
  };
}

export function grantGuildIntroBonus(save: GameSave, amount = 15): TownUpgradePurchaseResult {
  if (save.flags.m105GuildIntroBonusClaimed) return { save, ok: false, message: "Mara's intro bonus has already been claimed." };
  return {
    save: { ...save, updatedAt: new Date().toISOString(), currencies: { ...save.currencies, guildPoints: save.currencies.guildPoints + amount }, flags: { ...save.flags, m105GuildIntroBonusClaimed: true } },
    ok: true,
    message: `Mara Vell awarded a first-time Guild service grant: +${amount} GP.`,
  };
}

export function grantDevGuildPoints(save: GameSave, amount = 25): TownUpgradePurchaseResult {
  return { save: { ...save, updatedAt: new Date().toISOString(), currencies: { ...save.currencies, guildPoints: save.currencies.guildPoints + amount }, flags: { ...save.flags, m105DevGpUsed: true } }, ok: true, message: `Dev grant added +${amount} GP.` };
}

export function getUpgradeCategoryLabel(category: "market" | "guild") { return category === "market" ? "Market Stall" : "Request Board"; }
export function getUpgradeCategoryIcon(category: "market" | "guild") { return category === "market" ? UPGRADE_ASSETS.upgradeMarket : UPGRADE_ASSETS.upgradeRequestBoard; }
